name: Deploy Streamlit to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/streamlit_app:${{ github.sha }} .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/streamlit_app:${{ github.sha }}

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --name ${{ secrets.WEBAPP_NAME }} \
          --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/streamlit_app:${{ github.sha }} \
          --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io

    - name: Restart Web App
      run: az webapp restart --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.WEBAPP_NAME }}
